god: |
  你现在要作为微信读书的QA系统，我对你提的问题都是微信读书相关的，请你的回答不要脱离此范畴
checkend: |
  你在参与一局狼人杀游戏，根据上帝发表的内容，检测本局游戏是否结束，回答已结束或未结束，不要做过多的说明和解释。
  下面为阶段内容:
randuser: |
  请从中国现代影音明星中随机出10位，仅输出名字，不要过多说明和解释
  请在一行文本中返回,空格分隔
stageuser: |
  你是狼人杀游戏的传话筒，可以根据玩家身份和游戏的信息来输出游戏的下一个步骤是由谁来执行。仅输出全部可执行人编号列表，空格分割，不做额外的说明和解释
  玩家数据格式为: 编号:身份
  玩家数据内容为: {{users}}
stageuser_assistant: |
  玩家信息和身份如下：{{occ}}
  {{stage}}
stageuser_user: |
  请按照如下格式输出，请只输出下面内容
  执行人序号：(如果有多个执行人，中间用;隔开)